spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=2
        - id: carts-service
          uri: lb://carts-service
          predicates:
            - Path=/api/carts/**
          filters:
            - StripPrefix=2
        - id: discounts-service
          uri: lb://discounts-service
          predicates:
            - Path=/api/discounts/**
          filters:
            - StripPrefix=2
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=2
        - id: payments-service
          uri: lb://payments-service
          predicates:
            - Path=/api/payments/**
<<<<<<< HEAD
=======
>>>>>>> Stashed changes
>>>>>>> 5f0c30c8281501bfea11876340b5a57604bb4da9
          filters:
            - StripPrefix=2
